### ISSUE TITLE
Regarding strong name

### ISSUE THREAD

**Issue by jjsahalf** [StefanOssendorf/SecurityHeadersMiddleware#12]
I am trying to consume SecurityHeadersMiddleware.dll and SecurityHeadersMiddleware.OwinAppBuilder.dll  in our project which requires strong-named package. I found those two dlls are not strong named. Could you please make the packages signed and strong-named? Any suggestions or plans on this issue? Thank you very much, I really appreciate your help!

**Comment by StefanOssendorf** [comment]
Hi, unfortunately I won't provide/add a strong named package version of this - sorry.
I think the easiest way to do this is to create the strong-named package for yourself.
